project:
  type: website
  output-dir: docs

website:
  title: "EO Urban Monitoring"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: 01-intro.qmd
      - text: "Methods"
        href: 02-methods.qmd
    right:
      - icon: file-pdf
        text: "Download Full PDF"
        href: full-manual.pdf  # Link to the generated file

  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "1. Introduction"
        file: 01-intro.qmd
      - text: "2. Methodology"
        file: 02-methods.qmd
      - text: "3. Create annual Landsat composites"
        file: 03-code.qmd
      - text: "4. Train, validate and run a classifier"
        file: 04-classifier.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    title-block-banner: "#e2231a"
    title-block-banner-color: white
    code-copy: true
    toc: true
    highlight-style: github

  pdf:
    documentclass: report
    papersize: a4
    geometry:
      - margin=2.5cm
    number-sections: true
    toc: true
    header-includes: |
      \usepackage[default]{sourcesanspro}
      \usepackage{xcolor}
      \definecolor{kclred}{HTML}{e2231a}
      \usepackage{sectsty}
      \sectionfont{\color{kclred}}
      \chapterfont{\color{kclred}}
      \usepackage{fancyhdr}
      \pagestyle{fancy}
      \fancyhf{}
      \fancyhead[R]{José Gómez-Dans}
      \fancyfoot[C]{\thepage}